# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Wang Xin's Blog
author: Wang Xin
email: wangxin19930411@163.com
description: >- # this means to ignore newlines until "baseurl:"
    Welcome to my page, nice to see you!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://wangxin93.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  WangXin93
twitter_username: WangX93
# Enabling disqus comment
disqus:
    enable: false
    shortname: wangxin93
valine:
    enable: true
    leancloud_appid: z3odPusDI6yEgyXmIJgkmDf0-gzGzoHsz
    leancloud_appkey: iaCUG4aB5HWCFYnXmCRhatsM
    placeholder: Leave you comments here :-)
    visitor: true // 阅读量统计

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Enabling Excerpts on the Home Page
show_excerpts: False

# Enabling Google Analytics
google_analytics: UA-128271507-1

# Customize navigation links
header_pages:
  - blogs.md
  - about.md


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
